### ISSUE TITLE
Setup meeting: Data drafting instruction - with business area

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#170]
ES mentioned to us that there's a drafting instruction listing out what data we'll need to collect.

Acceptance Criteria:
- [x] offload to business area

**Comment by jaimiebutton** [comment]
Hey @hannavovk , did you mention we have a copy of this already in Teams?

**Comment by hannavovk** [comment]
Yes @jaimiebutton, the DIs is saved to the same folder as the calculator [Scrum Team -> CPR -> BCERS and OBPS](https://bcgov.sharepoint.com/:f:/t/00608-ScrumTeam/EkD7yaXycgFFuVaqQEzZk_0BBXXUpNps7ExPMy-uqyJslg?e=4aLCTN). What you'd need to look at is the table at the end.
Note that the DI only covers what reporting requirements need to be added to the reg, nit what's already required. For that it's best to look at the SWRS BC GHG rather than trying to read the reg.

**Comment by jaimiebutton** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-review/170?planning-poker) with Zenhub @nanyangpro

**Comment by Dianadec** [comment]
Meeting set for July 19 @ 1pm.

**Comment by Dianadec** [comment]
@hannavovk  I think this is considered done but let me know if we need anything else.
Outcome: Met with ES and team to go over next steps of data fields. Created word doc with meeting notes, saved in Data Modelling channel of DST teams.

**Comment by hannavovk** [comment]
Agreed, we can consider it done and we have a general plan for next steps. @jaimiebutton @Dianadec
