### ISSUE TITLE
Create a diagram of OBPS data

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-review#171]
Let's create a map of all the datafields we know we'll need in the OBPS system.

Acceptance Criteria:
- [ ] Create rough diagram of OBPS data/database structure
- [ ] For each datafield, add category such as 'reported by operator', 'released by program area', 'calculated by us', etc
- [ ] Pass diagram to Team Moose for feedback

Goal of ticket:
- Establish a concrete understanding of what data is needed and how it will be structured

**Comment by Dianadec** [comment]
@jaimiebutton we need more clarification on what the AC means by data/database structure.

**Comment by hannavovk** [comment]
Not sure exactly which data this ticket is referring to so may need a discussion. Current SWRS data is one ting but what we need for OBPS is another.

**Comment by andrea-williams** [comment]
I'm pretty confused by this ticket - is it for devs or UX? It *could* be a ticket for devs to create an ERD to capture database structure, but in order to do that we'd need input from UX re: what fields are needed. If this is a UX ticket, I presume it's blocked until the UX team has an opportunity to do more research with Clean Growth staff re: required data.

**Comment by jaimiebutton** [comment]
This was created with the intention of it being a dev ticket as some kind of data diagram, as that was mentioned in a conversation as something that might be helpful. That being said if it's not helpful right now, we can definitely get rid of this ticket. (Also happy to talk about it in backlog refinement.)

**Comment by Dianadec** [comment]
Closing - will create a new card to capture what actually needs to be done
